config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :apps do 
    resources :plats
    collection do
      get :archived
    end
  end

  resources :users do
    member do 
      get :api_token
      put :api_token, to: "users#refresh_api_token"
    end
  end

  resources :plats do
    resources :pkgs
  end

  resources :pkgs, only:[:show] do
    member do
      get :manifest
    end
  end

  resources :udid, only:[:create,:index] do
    collection do
      get "mobileconfig"
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  root "apps#index"

  post "api/pkgs" => "pkgs#api_create"

  put "api/plat/sort" => "plats#api_sort"

end

app/models/plat.rb
# == Schema Information
#
# Table name: plats
#
#  id             :integer          not null, primary key
#  name           :string
#  plat_name      :string
#  app_id         :integer
#  pkg_name       :string
#  packages_count :integer          default(0)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  bundle_id      :string
#  pkg_uniq       :boolean          default(TRUE)
#  user_id        :integer
#  deleted_at     :datetime
#

class Plat < ApplicationRecord
  acts_as_paranoid

  include PlatAble

  has_many :pkgs, :dependent => :destroy
  
  belongs_to :app
  belongs_to :user

  validates_presence_of :user_id

  enum plat_name: {
    ios: 'ios',
    android: 'android'
  }


  def bundle_id_reg
    if bundle_id.present?
      bundle_id_reg = bundle_id.gsub('.','\.').gsub('*','.*')
      bundle_id_reg = Regexp.new("^#{bundle_id_reg}")
    else
      /.*/
    end
  end

  def validate_pkg(pkg)
    if (bundle_id_reg =~ pkg.bundle_id) == nil
      raise "Bundle Id #{pkg.bundle_id} not match #{bundle_id}"
    end

    if pkg.plat_name != plat_name
      raise "Pkg Plat Validation Fail"
    end

    if pkg_uniq? && !pkg.uniq?
      raise "Pkg Uniq Validation Fail"
    end
  end

  
end

app/controllers/plats_controller.rb
class PlatsController < ApplicationController
  before_action :set_app, only: [:index, :show, :new, :create, :destroy, :api_sort]
  before_action :set_plat, only: [:show,:destroy,:update,:edit]

  def index
    @plats = Plat.where(app_id:params[:app_id])
    if @plats.present?
      redirect_to app_plat_path @plats.first.app, @plats.first
    else
      redirect_to new_app_plat_path @app
    end
  end

  def show
    @pkgs = @plat.pkgs.id_desc.page(params[:page]).per(params[:per])
    @plats = Plat.where(app_id:params[:app_id]).order(:sort,:id)
  end

  def new
    @plat = @app.plats.build
  end

  def create
    authorize!(:create, Plat)
    plat = Plat.create(plat_params.merge(user_id:current_user.id,sort:Plat.count))
    redirect_to app_plat_path @app, plat
  end

  def destroy
    authorize!(:destroy, @plat)
    @plat.destroy!
    @plats = Plat.where(app_id:params[:app_id])
    if @plats.first
      redirect_to app_plat_path @plats.first.app, @plats.first
    else
      redirect_to new_app_plat_path @app
    end
  end

  def edit
    render "new"
  end

  def update
    authorize!(:update, @plat)
    @plat.update(plat_params)
    redirect_to app_plat_path @plat.app, @plat
  end

  def api_sort
    authorize!(:sort, Plat)
    ids = params[:ids].split(",").map(&:to_i)
    plats = Plat.where(id:ids)
    map = plats.map { |e| [e.id,e] }.to_h
    ids.each_with_index do |id,index|
      plat = map[id]
      plat.update_column(:sort,index)
    end
  end

  private
  # # Use callbacks to share common setup or constraints between actions.
  def set_app
    @app = App.find(params[:app_id])
  end
  
  def set_plat
    @plat = Plat.find(params[:id])
  end

  # # Never trust parameters from the scary internet, only allow the white list through.
  def plat_params
    params.require(:plat).permit(:name,:app_id,:plat_name,:bundle_id,:pkg_uniq);
  end
end

app/helpers/plats_helper.rb
module PlatsHelper
  
  def pkg_selectable_map
    PkgAdapter.config.adapters.map{|k,v|{v[:des] => k}}.inject(:merge)
  end
end

app/views/plats/_cell.html.erb
<div class="col-md-12 cell">
  <a href="<%=pkg_path(pkg)%>">

    <div class="cell-container">
      <div class="icon">
        <%=image_tag(pkg.icon)%>
      </div>
      <div class="detail">
        <span class="title">
          <%=pkg.file_nick_name%>
          <span class="date-label tint-text">
            <%=time_ago_in_words pkg.created_at %>前
          </span>
        </span>

        <span class="sub-title">
         <%=pkg.name%> <span class="tint-text"><%="#{pkg.version}, build:#{pkg.build}"%></span>
        </span>
      
        <div class="actions">
          <% download_url = (browser.platform.android? || browser.platform.ios?) ? pkg.install_url : pkg.download_url %>

          <% unless (browser.platform.ios? && !pkg.ios?) || (browser.platform.android? && !pkg.android?) %>
            <a class="download-btn" href="<%=download_url%>">
              下载
            </a>
          <% end %>

          <% if can? :destroy, pkg %>
            <%=button_to '删除', plat_pkg_path(pkg.plat, pkg), form_class: "delete_btn", class:"btn-danger", data: {:confirm => 'Are you sure?'}, :method => :delete %>
          <% end %>
          
        </div>
      </div>
    </div>
    <div class="divider"></div>
  </a>
</div>

app/views/plats/new.html.erb
<%=render 'layouts/header'%>

<div class="container plat new">
    <%=form_for @plat, :url => @plat.persisted? ? app_plat_path(@plat.app,@plat) : app_plats_path, :html => { :method => @plat.new_record? ? "post" : "put", class: "app_form" } do |f|%>

    <%= hidden_field_tag "plat[app_id]", @plat.app_id %>

    <div class="title"><span> <%=@plat.persisted? ? "修改渠道" : "新建渠道" %> </span></div>

    <div class="form-group">
      <label for="plat_name">渠道名称*：</label>
      <%= f.text_field :name, class:"form-control", required:true %>
    </div>

    <div class="form-group">
      <label for="plat_name">校验包名：</label>
      <%= f.text_field :bundle_id, class:"form-control", placeholder:"不填则不校验,支持通配符*号" %>
    </div>

    <div class="form-group">
      <label for="plat_name">包类型*：</label>
      <%= f.select(:plat_name,pkg_selectable_map,{},{class:"form-control"}) %>
    </div>

    <div class="form-group">
      <label for="plat_name">不允许重复包：</label>
      <%= f.select(:pkg_uniq,{'YES'=>'true','NO'=>'false'},{},{class:"form-control"}) %>
    </div>

    <% if @plat.persisted? %>
      <%=f.submit "保存", class:"btn btn-primary ui-plat"%>
    <% else %>
      <%=f.submit "新建", class:"btn btn-primary ui-plat"%>
    <% end %>
    
  <%end%>
</div>

app/views/plats/show.html.erb
<%=render 'layouts/header'%>

<div class="container plat show app-host-container">

  <div class="visible-md visible-lg pull-right">

    <% if can? :destroy, @plat %>
      <%=link_to '删除', app_plat_path(@app, @plat), data: {:confirm => 'Are you sure?'}, class:"btn-danger", :method => :delete %>
    <% end %>

    <% if can? :update, @plat %>
      <%=link_to '修改', edit_app_plat_path(@app, @plat), class:"btn-info" %>
    <% end %>

  </div>

  <ul class="nav nav-tabs" id="nav_ul">
      <%@plats.each_with_index do |plat,index|%>
        <% if plat.id == params[:id].to_i %>
          <li data-id="<%=plat.id%>" role="presentation" class="active nav-tab-item"><%=link_to plat.name, app_plat_path(@app,plat) %></li>
        <% else %>
          <li data-id="<%=plat.id%>" role="presentation" class="nav-tab-item"><%=link_to plat.name, app_plat_path(@app,plat) %></li>
        <% end %>
      <% end %>
      <% if can? :create, Plat %>
        <li role="presentation" class="visible-md visible-lg nav-add-btn" id="nav_add_btn"><%=link_to '+', new_app_plat_path %></li>
      <% end %>
  </ul>

  <div class="row">
    <%=render partial: "cell", collection: @pkgs, as: :pkg %>
  </div>
  <div class="paginate">
    <%= paginate @pkgs %>
  </div>

  <div class="plat-info">
    <span>
      平台: <%=@plat.plat_des_name%> 包数: <%=@plat.pkgs.count%> 
      <% if @plat.bundle_id.present? %>
       包名: <%=@plat.bundle_id%>  
      <% end %>
    </span>
  </div>

  <% if can? :create, Pkg %>
    <div class="visible-md visible-lg pull-right">
      <%=link_to '上传', new_plat_pkg_path(@plat), class:"btn btn-primary ui-plat" %>
    </div>
  <% end %>


</div>

<script type="text/javascript">
  $(function(){
    //修改循序
    <% if can? :sort, Plat %>
      var add_btn = null;
      var list = document.getElementById("nav_ul");
      Sortable.create(list,
        {filter:".nav-add-btn",
          onStart: function (evt) {
            console.log('onStart')
            add_btn = $("#nav_add_btn")
            $(add_btn).remove()
          },
          onEnd: function (evt) {
            console.log('onEnd')
            var ids = $(".nav-tab-item").map(function(){
              return $(this).data("id")
            }).get()

            $.ajax({
              url: '/api/plat/sort',
              type: 'PUT',
              data: {ids: ids.join(','),app_id:<%=params[:app_id]%>},
            })
            .fail(function() {
              alert("修改顺序失败")
              location.reload();
            })

            $("#nav_ul").append(add_btn)
          }}
        );
    <% end %>
  })
</script>