config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :apps do 
    resources :plats
    collection do
      get :archived
    end
  end

  resources :users do
    member do 
      get :api_token
      put :api_token, to: "users#refresh_api_token"
    end
  end

  resources :plats do
    resources :pkgs
  end

  resources :pkgs, only:[:show] do
    member do
      get :manifest
    end
  end

  resources :udid, only:[:create,:index] do
    collection do
      get "mobileconfig"
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  root "apps#index"

  post "api/pkgs" => "pkgs#api_create"

  put "api/plat/sort" => "plats#api_sort"

end

app/views/apps/_cell.html.erb
<div class="col-md-4 cell">
  <% last_pkg = app.pkgs.last%>
  <a href="<%=app_plats_path(app)%>">
    <div class="cell-container">
      <div class="icon">
        <% if app.icon %>
          <%=image_tag(app.icon)%>  
        <% else %>
          <div class="text-icon"><span><%=app.name[0,1]%></span></div>
        <% end %>
      </div>
      <div class="detail">
        <span class="title">
          <%=app.name%>
          <span class="date-label">
            <% if last_pkg.present? %>
              <%=time_ago_in_words(last_pkg.updated_at)%>前
            <% end %>
          </span>
        </span>
        <div class="halving-line">---</div>

        <span class="sub-title">
          包总数：<span><%=app.pkgs.count%></span>
        </span> 
        <span class="sub-title">
          渠道数：<span><%=app.plats.count%></span>
        </span>
        <% if last_pkg.present? %>
          <span class="sub-title visible-md visible-lg">
            最新包：<span><%=last_pkg.build%> <%=last_pkg.plat&.name%></span>
          </span>
        <% end %>
       
      </div>

    </div>
    <div class="divider"></div>
  </a>

  <div class="actions visible-md visible-lg pull-right">
    <% if can? :destroy, app %>
      <%=link_to "", app_path(app), data: {:confirm => 'Are you sure?'}, class:"glyphicon glyphicon-remove", :method => :delete %>
    <% end %>
    
    <% if can? :update, app %>
      <%=link_to "", edit_app_path(app), class:"glyphicon glyphicon-cog" %>
    <% end %>
    
  </div>
  
</div>

app/views/apps/_cell_add.html.erb
<div class="col-md-4 cell new">
  <a href="/apps/new">
    <div class="cell-container">
      <span class="glyphicon glyphicon-console" aria-hidden="true"></span>
      <span>New APP</span>
    </div>
    <div class="divider"></div>
  </a>
</div>

app/views/apps/archived.html.erb
<%=render 'layouts/header'%>

<div class="container app index app-host-container">

<%=render 'comoms/alert'%>

<div class="row">  
  <%= render partial: "cell", collection: @apps, as: :app %>
</div>

</div>

app/views/apps/index.html.erb
<%=render 'layouts/header'%>

<div class="container app index app-host-container">

<%=render 'comoms/alert'%>

<div class="row">
  <% if can? :create, App %>
    <div class="visible-md visible-lg">
      <%=render "cell_add" %>
    </div>
  <% end %>
  
  <%= render partial: "cell", collection: @apps, as: :app %>

  <% if @has_archived %>
    <div class="col-md-4 cell archived">
      <a href="/apps/archived">
        <div class="cell-container">
          <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
          <span>Archived</span>
        </div>
        <div class="divider"></div>
      </a>
    </div>
  <% end %>
  
</div>

</div>

app/views/apps/new.html.erb
<%=render 'layouts/header'%>

<div class="container app new">
  <%=render 'comoms/alert'%>
  <%=form_for @app, :html => { class: "app_form" } do |f|%>
    <div class="title"><span>
    <% if @app.persisted? %>
      修改应用
    <% else %>
      新建应用
    <% end %>
    </span></div>
      <div class="form-group">
        <label for="app_name">应用名称*：</label>
        <%= f.text_field :name, class:"form-control", required:true %>
      </div>

      <% if @app.persisted? %>
      <div class="form-group">
        <label for="app_archive">归档：</label>
        <%= f.check_box :archived %>
        </div>
      <% end %>
      
    <%=f.submit @app.persisted? ? "保存" : "新建", class:"btn btn-primary ui-plat"%>
  <%end%>
</div>